#!/bin/sh
#
# Copyright (C) 2017  Savoir-faire Linux Inc.
#	Vivien Didelot <vivien.didelot@savoirfairelinux.com>
#	Gaël Portay <gael.portay@savoirfairelinux.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#

if [ "$1" ]; then
	echo "$1" | "$0"
	exit
fi

exec nc -NU /tmp/qurlew.socket
